default: &default
  host: 'oss.aliyuncs.com'
  access_key_id: 'VoCEyHuAEm21EcuE'
  secret_access_key: 'CUXT5qBXHOyk6bXrL5mkuB7InuBkkq'
  bucket: "j-assets"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
