---
chdir: /home/outman/apps/hncsd
environment: production
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
socket: tmp/sockets/thin.sock
daemonize: true
